baseURL: http://example.org/
languageCode: en-us
title: Lawyer Hugo Grotius
theme: hugo-theme-notrack
newContentEditor: nvim
mainSections: blog
paginate: 4
params:
  author: Hugo de Groot
  blogLatestHeading: My writing
  favicon: hugo_grotius.png
  mainSections: blog
  nBlogLatest: 4
  showBlogLatest: yes
  showTaxonomyLinks: no
  siteHeading: Hugo Grotius
  social:
    email: example@example.com
    github: example
    keybase: example
    linkedin: example
    mastodon: example
    rss: rss won't use the value you give it so you can put anything here
taxonomies:
  categories: categories
  month: month
  tags: tags
  year: year
permalinks:
  blog: /blog/:year/:month/:slug
